"""
Django settings for devicecheck_backend project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or os.environ.get('SECRET_KEY', '')
if not SECRET_KEY.strip():
    raise ImproperlyConfigured('Configure DJANGO_SECRET_KEY no ambiente do servidor.')

# SECURITY WARNING: don't run with debug turned on in production!
def env_bool(name, default=False):
    value = os.environ.get(name, str(default)).strip().lower()
    if value not in {'1', 'true', 'yes', '0', 'false', 'no'}:
        raise ImproperlyConfigured(f'{name} deve ser true ou false.')
    return value in {'1', 'true', 'yes'}


DEBUG = env_bool('DJANGO_DEBUG')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Informe somente hostnames, sem protocolo ou caminho. Em desenvolvimento, inclua
# aqui via ambiente o hostname HTTPS atribuído pelo ngrok.
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
if not DEBUG and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured('Configure DJANGO_ALLOWED_HOSTS sem wildcard em produção.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'devicecheck_backend.observability.OperationalEventsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devicecheck_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devicecheck_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {'client_encoding': 'UTF8'},
    }
}
if os.environ.get('DATABASE_URL'):
    try:
        DATABASES['default'] = dj_database_url.parse(os.environ['DATABASE_URL'])
    except (ValueError, KeyError, TypeError):
        # Erros do parser podem incluir a URL com senha; não propagar seu texto.
        raise ImproperlyConfigured('DATABASE_URL inválida; configure uma URL PostgreSQL.') from None
    if DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
        raise ImproperlyConfigured('DATABASE_URL deve usar PostgreSQL.')

_database = DATABASES['default']
_database['CONN_MAX_AGE'] = int(os.environ.get('DB_CONN_MAX_AGE', '0'))
_database['CONN_HEALTH_CHECKS'] = True
_database.setdefault('OPTIONS', {}).setdefault('client_encoding', 'UTF8')
_database['OPTIONS'].setdefault('connect_timeout', int(os.environ.get('DB_CONNECT_TIMEOUT', '5')))
if os.environ.get('DB_SSLMODE'):
    _database['OPTIONS']['sslmode'] = os.environ['DB_SSLMODE']
if os.environ.get('DB_SSLROOTCERT'):
    _database['OPTIONS']['sslrootcert'] = os.environ['DB_SSLROOTCERT']


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get('DJANGO_STATIC_ROOT') or BASE_DIR / 'staticfiles')
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}
# Uploads não são servidos por WhiteNoise nem por uma rota pública de desenvolvimento.
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT') or BASE_DIR / 'media')
MEDIA_URL = '/media/'

# Ative HTTPS no servidor/proxy de produção; não aplicar ao runserver local.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT')
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS')
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
# Somente atrás de um proxy confiável que sobrescreve o header recebido do cliente.
if env_bool('DJANGO_TRUST_PROXY_SSL_HEADER'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = ('django.core.mail.backends.console.EmailBackend' if DEBUG
                 else 'django.core.mail.backends.dummy.EmailBackend')


def env_nonnegative_int(name, default=0):
    raw_value = os.environ.get(name, str(default)).strip()
    if not raw_value.isdigit():
        raise ImproperlyConfigured(f'{name} deve ser um número inteiro não negativo.')
    value = int(raw_value)
    if value > 32:
        raise ImproperlyConfigured(f'{name} excede o limite operacional aceito.')
    return value


def env_rate(name, default):
    value = os.environ.get(name, default).strip().lower()
    parts = value.split('/')
    allowed_periods = {
        's', 'sec', 'second', 'seconds', 'm', 'min', 'minute', 'minutes',
        'h', 'hour', 'hours', 'd', 'day', 'days',
    }
    if len(parts) != 2 or not parts[0].isdigit() or int(parts[0]) < 1 or parts[1] not in allowed_periods:
        raise ImproperlyConfigured(
            f'{name} deve usar o formato positivo quantidade/período, por exemplo 30/min.'
        )
    return value


DIAGPRO_THROTTLE_RATES = {
    'auth_ip': env_rate('DJANGO_THROTTLE_AUTH_IP_RATE', '30/min'),
    'auth_account': env_rate('DJANGO_THROTTLE_AUTH_ACCOUNT_RATE', '10/min'),
    'refresh': env_rate('DJANGO_THROTTLE_REFRESH_RATE', '60/min'),
    'read': env_rate('DJANGO_THROTTLE_READ_RATE', '300/min'),
    'write': env_rate('DJANGO_THROTTLE_WRITE_RATE', '60/min'),
    'diagnostic': env_rate('DJANGO_THROTTLE_DIAGNOSTIC_RATE', '60/min'),
    'remediation': env_rate('DJANGO_THROTTLE_REMEDIATION_RATE', '60/min'),
    'password': env_rate('DJANGO_THROTTLE_PASSWORD_RATE', '5/hour'),
    'checkout': env_rate('DJANGO_THROTTLE_CHECKOUT_RATE', '10/min'),
    'webhook': env_rate('DJANGO_THROTTLE_WEBHOOK_RATE', '300/min'),
    'health': env_rate('DJANGO_THROTTLE_HEALTH_RATE', '120/min'),
}
DIAGPRO_THROTTLE_CACHE_ALIAS = 'throttle'
DIAGPRO_NUM_PROXIES = env_nonnegative_int('DJANGO_NUM_PROXIES')
DIAGPRO_THROTTLE_CACHE_URL = os.environ.get('DJANGO_THROTTLE_CACHE_URL', '').strip()
if DIAGPRO_THROTTLE_CACHE_URL and not DIAGPRO_THROTTLE_CACHE_URL.startswith(('redis://', 'rediss://')):
    raise ImproperlyConfigured('DJANGO_THROTTLE_CACHE_URL deve usar redis:// ou rediss://.')
DIAGPRO_REQUIRE_SHARED_THROTTLE_CACHE = env_bool(
    'DJANGO_REQUIRE_SHARED_THROTTLE_CACHE',
    not DEBUG,
)
if DIAGPRO_REQUIRE_SHARED_THROTTLE_CACHE and not DIAGPRO_THROTTLE_CACHE_URL:
    raise ImproperlyConfigured(
        'Configure DJANGO_THROTTLE_CACHE_URL com Redis antes de executar em produção.'
    )

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'diagpro-default-local',
    },
    DIAGPRO_THROTTLE_CACHE_ALIAS: (
        {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': DIAGPRO_THROTTLE_CACHE_URL,
            'KEY_PREFIX': 'diagpro',
        }
        if DIAGPRO_THROTTLE_CACHE_URL else
        {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'diagpro-throttle-local',
            'KEY_PREFIX': 'diagpro',
        }
    ),
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'core.throttling.DiagProScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': DIAGPRO_THROTTLE_RATES,
    # Zero ignora X-Forwarded-For. Produção deve informar a quantidade exata
    # de proxies confiáveis que sobrescrevem esse header.
    'NUM_PROXIES': DIAGPRO_NUM_PROXIES,
}

SIMPLE_JWT = {
    'CHECK_REVOKE_TOKEN': True,
}
_development_cors_origins = 'http://localhost:5173,http://127.0.0.1:5173,null,file://' if DEBUG else ''
CORS_ALLOWED_ORIGINS = env_list('DJANGO_CORS_ALLOWED_ORIGINS', _development_cors_origins)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = False
CORS_URLS_REGEX = r'^/api/.*$'

DIAGPRO_HEALTHCHECK_DATABASE = env_bool('DJANGO_HEALTHCHECK_DATABASE', True)
_log_level = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()
if _log_level not in {'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'}:
    raise ImproperlyConfigured('DJANGO_LOG_LEVEL inválido.')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {'safe': {'()': 'devicecheck_backend.observability.SafeJsonFormatter'}},
    'handlers': {'console': {
        'class': 'logging.StreamHandler', 'stream': 'ext://sys.stdout', 'formatter': 'safe',
    }},
    'root': {'handlers': ['console'], 'level': _log_level},
    'loggers': {
        name: {'handlers': ['console'], 'level': _log_level, 'propagate': False}
        for name in ('django', 'django.server', 'diagpro', 'waitress')
    },
}

# Mercado Pago: credenciais e URLs existem somente no backend.
MERCADO_PAGO_ACCESS_TOKEN = os.environ.get('MERCADO_PAGO_ACCESS_TOKEN', '')
MERCADO_PAGO_WEBHOOK_SECRET = os.environ.get('MERCADO_PAGO_WEBHOOK_SECRET', '')
MERCADO_PAGO_SUCCESS_URL = os.environ.get('MERCADO_PAGO_SUCCESS_URL', '')
MERCADO_PAGO_FAILURE_URL = os.environ.get('MERCADO_PAGO_FAILURE_URL', '')
MERCADO_PAGO_PENDING_URL = os.environ.get('MERCADO_PAGO_PENDING_URL', '')
MERCADO_PAGO_WEBHOOK_URL = os.environ.get('MERCADO_PAGO_WEBHOOK_URL', '')
MERCADO_PAGO_USE_SANDBOX = os.environ.get('MERCADO_PAGO_USE_SANDBOX', 'true').lower() in {'1', 'true', 'yes'}
MERCADO_PAGO_TIMEOUT_SECONDS = int(os.environ.get('MERCADO_PAGO_TIMEOUT_SECONDS', '10'))
MERCADO_PAGO_LICENSE_DURATION_DAYS = int(os.environ.get('MERCADO_PAGO_LICENSE_DURATION_DAYS', '30'))
