const PATCH_AGE_THRESHOLDS_DAYS = Object.freeze({ low: 180, medium: 365, high: 730 })

const DEVICE_RULES = Object.freeze([
  {
    id: 'device.security_patch_age.low', category: 'outdated_security_patch',
    title: 'Patch de segurança desatualizado', severity: 'low', evidenceConfidence: 'high',
    description: 'O patch tem mais de 180 e no máximo 365 dias.',
    conditions: [
      { fact: 'securityPatch.ageDays', operator: 'gt', value: PATCH_AGE_THRESHOLDS_DAYS.low },
      { fact: 'securityPatch.ageDays', operator: 'lte', value: PATCH_AGE_THRESHOLDS_DAYS.medium },
    ],
    evidenceFacts: ['securityPatch.ageDays'], dedupeGroup: 'device.security_patch_age',
    summary: 'O patch de segurança está significativamente antigo, mas isso não representa detecção de ameaça.',
    technicalExplanation: 'A idade foi calculada entre a data informada por ro.build.version.security_patch e a data da análise.',
    recommendation: 'Verifique se o fabricante oferece uma atualização oficial de segurança.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.security_patch_age.medium', category: 'outdated_security_patch',
    title: 'Patch de segurança desatualizado', severity: 'medium', evidenceConfidence: 'high',
    description: 'O patch tem mais de 365 e no máximo 730 dias.',
    conditions: [
      { fact: 'securityPatch.ageDays', operator: 'gt', value: PATCH_AGE_THRESHOLDS_DAYS.medium },
      { fact: 'securityPatch.ageDays', operator: 'lte', value: PATCH_AGE_THRESHOLDS_DAYS.high },
    ],
    evidenceFacts: ['securityPatch.ageDays'], dedupeGroup: 'device.security_patch_age',
    summary: 'O patch de segurança está desatualizado e o dispositivo pode não possuir correções recentes.',
    technicalExplanation: 'Este finding descreve atraso de manutenção; não indica malware ou comprometimento.',
    recommendation: 'Procure uma atualização oficial do Android ou orientação do fabricante.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.security_patch_age.high', category: 'outdated_security_patch',
    title: 'Patch de segurança muito desatualizado', severity: 'high', evidenceConfidence: 'high',
    description: 'O patch tem mais de 730 dias.',
    conditions: [{ fact: 'securityPatch.ageDays', operator: 'gt', value: PATCH_AGE_THRESHOLDS_DAYS.high }],
    evidenceFacts: ['securityPatch.ageDays'], dedupeGroup: 'device.security_patch_age',
    summary: 'O patch informado está há mais de dois anos sem atualização de segurança.',
    technicalExplanation: 'A classificação reflete apenas a idade do patch declarado pelo sistema.',
    recommendation: 'Priorize uma atualização oficial ou avalie a substituição do dispositivo quando não houver suporte.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.debuggable_build', category: 'modified_environment',
    title: 'Build Android marcada como depurável', severity: 'medium', evidenceConfidence: 'high',
    conditions: [{ fact: 'build.debuggable', operator: 'equals', value: true }],
    evidenceFacts: ['build.debuggable'],
    summary: 'A build apresenta uma característica de desenvolvimento ou customização.',
    technicalExplanation: 'ro.debuggable=1 amplia recursos de depuração, mas não comprova root nem malware.',
    recommendation: 'Confirme se a build de desenvolvimento é intencional; em produção, prefira firmware oficial.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.insecure_build', category: 'modified_environment',
    title: 'Build Android com modo seguro desativado', severity: 'high', evidenceConfidence: 'high',
    conditions: [{ fact: 'build.secure', operator: 'equals', value: false }],
    evidenceFacts: ['build.secure'],
    summary: 'A configuração da build é menos restritiva que a esperada em um firmware de produção.',
    technicalExplanation: 'ro.secure=0 é um sinal de configuração da build e não comprova comprometimento.',
    recommendation: 'Valide a origem do firmware e considere restaurar uma versão oficial.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.test_keys_build', category: 'modified_environment',
    title: 'Build assinada com test-keys', severity: 'low', evidenceConfidence: 'high',
    conditions: [{ fact: 'build.testKeys', operator: 'equals', value: true }],
    evidenceFacts: ['build.testKeys'],
    summary: 'A build usa chaves comuns em ambientes de desenvolvimento ou sistemas personalizados.',
    technicalExplanation: 'A tag test-keys, isoladamente, não demonstra root, malware ou comprometimento.',
    recommendation: 'Confirme se a instalação de uma build personalizada foi intencional e confiável.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.package_verifier_disabled', category: 'security_configuration',
    title: 'Verificação de pacotes desativada', severity: 'medium', evidenceConfidence: 'high',
    conditions: [{ fact: 'packageVerifier.enabled', operator: 'equals', value: false }],
    evidenceFacts: ['packageVerifier.enabled'],
    summary: 'Uma proteção de verificação do Android está desativada.',
    technicalExplanation: 'A configuração reduz uma camada preventiva, mas não demonstra a presença de malware.',
    recommendation: 'Reative a verificação de aplicativos nas configurações do Android, quando disponível.',
    remediation: { available: true, type: 'manual_guidance' },
  },
  {
    id: 'device.su_binary_accessible', category: 'modified_environment',
    title: 'Executável su acessível ao shell ADB', severity: 'high', evidenceConfidence: 'medium',
    conditions: [{ fact: 'root.suAccessible', operator: 'equals', value: true }],
    evidenceFacts: ['root.suAccessible'],
    summary: 'Foi observado um sinal técnico de ambiente modificado ou acesso administrativo.',
    technicalExplanation: 'A presença de su não identifica a origem da modificação e não é uma detecção de malware.',
    recommendation: 'Confirme se o acesso administrativo foi habilitado intencionalmente.',
    remediation: { available: false, type: 'manual_guidance' },
  },
])

const USER_APP = { fact: 'app.type', operator: 'equals', value: 'user' }

const APP_RULES = Object.freeze([
  {
    id: 'app.accessibility_overlay.adb_origin', category: 'sensitive_capability_combination',
    title: 'Capacidades sensíveis combinadas em app instalado via ADB', severity: 'high', evidenceConfidence: 'high',
    conditions: [USER_APP,
      { fact: 'capabilities.ACCESSIBILITY.verified', operator: 'equals', value: true },
      { fact: 'capabilities.OVERLAY.effective', operator: 'equals', value: true },
      { fact: 'origin.type', operator: 'equals', value: 'adb' },
    ],
    evidenceFacts: ['capabilities.ACCESSIBILITY.verified', 'capabilities.OVERLAY.effective', 'origin.type', 'app.type'],
    dedupeGroup: 'app.accessibility_overlay',
    summary: 'O app combina acessibilidade habilitada, overlay efetivo e instalação identificada via ADB.',
    technicalExplanation: 'A combinação pode permitir interações invasivas, porém não comprova comportamento malicioso.',
    recommendation: 'Revise a finalidade e a origem do aplicativo; considere remoção apenas se ele não for reconhecido.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.accessibility_overlay.unknown_origin', category: 'sensitive_capability_combination',
    title: 'Capacidades sensíveis com origem não determinada', severity: 'high', evidenceConfidence: 'medium',
    conditions: [USER_APP,
      { fact: 'capabilities.ACCESSIBILITY.verified', operator: 'equals', value: true },
      { fact: 'capabilities.OVERLAY.effective', operator: 'equals', value: true },
      { fact: 'origin.type', operator: 'equals', value: 'unknown' },
    ],
    evidenceFacts: ['capabilities.ACCESSIBILITY.verified', 'capabilities.OVERLAY.effective', 'origin.type', 'app.type'],
    dedupeGroup: 'app.accessibility_overlay',
    summary: 'O app combina acessibilidade e overlay efetivos, mas sua origem não pôde ser determinada.',
    technicalExplanation: 'Origem desconhecida reduz a qualidade contextual; não equivale a instalação maliciosa.',
    recommendation: 'Confirme com o cliente a finalidade e a origem do aplicativo antes de qualquer ação.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.accessibility_overlay', category: 'sensitive_capability_combination',
    title: 'Acessibilidade e sobreposição de tela habilitadas', severity: 'medium', evidenceConfidence: 'high',
    conditions: [USER_APP,
      { fact: 'capabilities.ACCESSIBILITY.verified', operator: 'equals', value: true },
      { fact: 'capabilities.OVERLAY.effective', operator: 'equals', value: true },
    ],
    evidenceFacts: ['capabilities.ACCESSIBILITY.verified', 'capabilities.OVERLAY.effective', 'app.type'],
    dedupeGroup: 'app.accessibility_overlay',
    summary: 'O aplicativo combina duas capacidades que merecem revisão contextual.',
    technicalExplanation: 'AppOps confirmou overlay e o serviço de acessibilidade aparece habilitado. Apps legítimos também podem usar essa combinação.',
    recommendation: 'Verifique se as duas capacidades são necessárias para a função esperada do aplicativo.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.accessibility_package_install', category: 'sensitive_capability_combination',
    title: 'Acessibilidade e instalação de pacotes habilitadas', severity: 'medium', evidenceConfidence: 'high',
    conditions: [USER_APP,
      { fact: 'capabilities.ACCESSIBILITY.verified', operator: 'equals', value: true },
      { fact: 'capabilities.PACKAGE_INSTALL.effective', operator: 'equals', value: true },
    ],
    evidenceFacts: ['capabilities.ACCESSIBILITY.verified', 'capabilities.PACKAGE_INSTALL.effective', 'app.type'],
    summary: 'O app combina acessibilidade com capacidade efetiva de solicitar instalação de pacotes.',
    technicalExplanation: 'A combinação merece revisão, mas pode existir em ferramentas legítimas de suporte ou automação.',
    recommendation: 'Verifique a origem e a necessidade das capacidades antes de considerar remoção.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.package_install.adb_origin', category: 'sensitive_capability_combination',
    title: 'Instalação de pacotes em app instalado via ADB', severity: 'medium', evidenceConfidence: 'high',
    conditions: [USER_APP,
      { fact: 'capabilities.PACKAGE_INSTALL.effective', operator: 'equals', value: true },
      { fact: 'origin.type', operator: 'equals', value: 'adb' },
    ],
    evidenceFacts: ['capabilities.PACKAGE_INSTALL.effective', 'origin.type', 'app.type'],
    summary: 'O app foi instalado via ADB e possui capacidade efetiva para solicitar instalação de outros pacotes.',
    technicalExplanation: 'A correlação merece revisão de procedência, sem indicar malware por si só.',
    recommendation: 'Confirme a procedência e a necessidade funcional do aplicativo.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.sms_contacts_boot', category: 'sensitive_capability_combination',
    title: 'Conjunto de capacidades sensíveis', severity: 'medium', evidenceConfidence: 'medium',
    conditions: [USER_APP,
      { fact: 'capabilities.SMS.verified', operator: 'equals', value: true },
      { fact: 'capabilities.CONTACTS.verified', operator: 'equals', value: true },
      { fact: 'capabilities.BOOT.verified', operator: 'equals', value: true },
    ],
    evidenceFacts: ['capabilities.SMS.verified', 'capabilities.CONTACTS.verified', 'capabilities.BOOT.verified', 'app.type'],
    summary: 'O app reúne acesso a SMS, contatos e inicialização automática.',
    technicalExplanation: 'As concessões foram reportadas pelo Package Manager; a combinação não demonstra uso abusivo.',
    recommendation: 'Verifique se o conjunto de permissões é compatível com a finalidade conhecida do aplicativo.',
    remediation: { available: true, type: 'uninstall_user_app' },
  },
  {
    id: 'app.device_admin.untrusted_context', category: 'device_administrator_context',
    title: 'Administrador do dispositivo com contexto sensível', severity: 'high', evidenceConfidence: 'medium',
    conditions: [USER_APP,
      { fact: 'deviceAdmin.active', operator: 'equals', value: true },
      { fact: 'origin.untrusted', operator: 'equals', value: true },
      { fact: 'highImpactCount', operator: 'gte', value: 1 },
    ],
    evidenceFacts: ['deviceAdmin.active', 'origin.untrusted', 'highImpactCount', 'app.type'],
    dedupeGroup: 'app.device_admin_context',
    summary: 'O app é administrador do dispositivo, possui capacidade sensível e sua origem é ADB ou não determinada.',
    technicalExplanation: 'Device Admin pode ser legítimo; por segurança, sua desativação exige revisão manual no Android.',
    recommendation: 'Confirme a finalidade com o cliente e revise manualmente o privilégio de administrador.',
    remediation: { available: false, type: 'manual_guidance' },
  },
  {
    id: 'app.device_admin.multiple_capabilities', category: 'device_administrator_context',
    title: 'Administrador do dispositivo com múltiplas capacidades', severity: 'medium', evidenceConfidence: 'high',
    conditions: [USER_APP,
      { fact: 'deviceAdmin.active', operator: 'equals', value: true },
      { fact: 'highImpactCount', operator: 'gte', value: 2 },
    ],
    evidenceFacts: ['deviceAdmin.active', 'highImpactCount', 'app.type'],
    dedupeGroup: 'app.device_admin_context',
    summary: 'O app combina privilégio de administrador com múltiplas capacidades sensíveis verificadas.',
    technicalExplanation: 'A combinação merece validação, mas não identifica atividade maliciosa.',
    recommendation: 'Revise manualmente as capacidades e o privilégio de administrador.',
    remediation: { available: false, type: 'manual_guidance' },
  },
])

const DECLARATIVE_RULES = Object.freeze([...DEVICE_RULES, ...APP_RULES])

module.exports = { APP_RULES, DECLARATIVE_RULES, DEVICE_RULES, PATCH_AGE_THRESHOLDS_DAYS }
