# Generated by Django 6.1 on 2026-08-11 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('android', 'Android'), ('ios', 'iPhone'), ('pc', 'Computador')], max_length=10)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('sistema_operacional', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_geral', models.PositiveSmallIntegerField(default=0)),
                ('score_seguranca', models.PositiveSmallIntegerField(default=0)),
                ('score_bateria', models.PositiveSmallIntegerField(default=0)),
                ('score_armazenamento', models.PositiveSmallIntegerField(default=0)),
                ('score_performance', models.PositiveSmallIntegerField(default=0)),
                ('score_sistema', models.PositiveSmallIntegerField(default=0)),
                ('dados_brutos', models.JSONField(blank=True, default=dict)),
                ('resumo_ia', models.TextField(blank=True)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='core.dispositivo')),
            ],
        ),
    ]
