# Generated by Django 6.1 on 2026-08-11 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dispositivo_analise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plano', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual'), ('empresarial', 'Empresarial')], default='mensal', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenca', to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('analise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='core.analise')),
            ],
        ),
    ]
