# Generated by Django 6.1 on 2026-08-28 00:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_licenca_relatorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=128)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('versao_android', models.CharField(blank=True, max_length=50)),
                ('sdk', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('security_patch', models.DateField(blank=True, null=True)),
                ('modo', models.CharField(choices=[('quick', 'Rápida'), ('complete', 'Completa'), ('custom', 'Personalizada')], max_length=20)),
                ('modulos', models.JSONField(default=list)),
                ('iniciado_em', models.DateTimeField()),
                ('finalizado_em', models.DateTimeField(db_index=True)),
                ('health_available', models.BooleanField(blank=True, null=True)),
                ('health_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_label', models.CharField(blank=True, max_length=80)),
                ('health_explanation', models.TextField(blank=True)),
                ('bateria', models.JSONField(blank=True, null=True)),
                ('armazenamento', models.JSONField(blank=True, null=True)),
                ('memoria', models.JSONField(blank=True, null=True)),
                ('apps', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('stages', models.JSONField(blank=True, default=dict)),
                ('resultado_tecnico', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finalizado_em', '-id'],
                'indexes': [models.Index(fields=['usuario', '-finalizado_em'], name='diag_user_finished_idx'), models.Index(fields=['usuario', 'serial', '-finalizado_em'], name='diag_user_serial_idx')],
            },
        ),
    ]
