# Generated by Django 6.1 on 2026-08-30 16:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plano_and_subscription_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mercadopago', editable=False, max_length=30)),
                ('external_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('external_preference_id', models.CharField(blank=True, db_index=True, max_length=180)),
                ('external_payment_id', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('status', models.CharField(choices=[('checkout_created', 'Checkout criado'), ('pending', 'Pagamento pendente'), ('approved', 'Pagamento aprovado'), ('rejected', 'Pagamento recusado'), ('canceled', 'Pagamento cancelado'), ('refunded', 'Pagamento reembolsado'), ('charged_back', 'Pagamento contestado'), ('invalid', 'Pagamento inválido'), ('failed', 'Falha de integração')], db_index=True, default='checkout_created', max_length=30)),
                ('provider_status', models.CharField(blank=True, max_length=60)),
                ('provider_status_detail', models.CharField(blank=True, max_length=180)),
                ('valor_esperado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('moeda', models.CharField(max_length=3)),
                ('checkout_url', models.URLField(blank=True, max_length=600)),
                ('sandbox', models.BooleanField(default=True)),
                ('webhook_count', models.PositiveIntegerField(default=0)),
                ('ultimo_webhook_request_id', models.CharField(blank=True, max_length=180)),
                ('erro_codigo', models.CharField(blank=True, max_length=80)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('ativado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='core.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['usuario', '-criado_em'], name='payment_user_created_idx')],
            },
        ),
    ]
