# Generated by Django 6.1 on 2026-09-01 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_id', models.CharField(max_length=400)),
                ('rule_id', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('device', 'Dispositivo'), ('app', 'Aplicativo')], max_length=20)),
                ('subject_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=20)),
                ('evidence_confidence', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('reviewed', 'Revisado'), ('remediation_pending', 'Remediação pendente'), ('resolved', 'Resolvido'), ('verification_failed', 'Verificação falhou'), ('dismissed', 'Descartado')], default='open', max_length=30)),
                ('recommendation', models.TextField(blank=True)),
                ('remediation_type', models.CharField(blank=True, max_length=50)),
                ('remediation_available', models.BooleanField(default=False)),
                ('evidence', models.JSONField(default=list)),
                ('score_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scorer_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-diagnostico__finalizado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='scan_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='security_risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='security_risk_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='security_risk_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='security_risk_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='security_schema_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='diagnostico',
            index=models.Index(fields=['usuario', 'security_risk_level', '-finalizado_em'], name='diag_user_risk_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnostico',
            constraint=models.UniqueConstraint(condition=models.Q(('scan_id__isnull', False)), fields=('usuario', 'scan_id'), name='diag_user_scan_unique'),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_findings', to='core.diagnostico'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['rule_id'], name='secfind_rule_idx'),
        ),
        migrations.AddIndex(
            model_name='securityfinding',
            index=models.Index(fields=['severity', 'category', 'status'], name='secfind_filter_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityfinding',
            constraint=models.UniqueConstraint(fields=('diagnostico', 'rule_id', 'subject_type', 'subject_id'), name='uniq_diag_security_finding'),
        ),
    ]
